### ISSUE TITLE
Open source training dataset

### ISSUE THREAD

**Issue by liyaooi** [scutcyr/SoulChat#1]
Hello, I greatly admire your work. I was wondering if you would consider open-sourcing the training dataset? Such as SoulChatCorpus-single_turn, SoulChatCorpus-multi_turn and SoulChatCorpus? 

It would be tremendously beneficial for the development of the entire community. If it has already been open-sourced, could you please provide me with a download link? Thank you very much.

**Comment by qiuhuachuan** [comment]
For a large-scale and multi-turn dialogue dataset in mental health support, please see this repo https://github.com/qiuhuachuan/smile

**Comment by scutcyr** [comment]
SoulChatCorpus-multi_turn: https://www.modelscope.cn/datasets/YIRONGCHEN/SoulChatCorpus
