### ISSUE TITLE
请问文中提到的单轮和多轮数据集方便公开么

### ISSUE THREAD

**Issue by wanghao07456** [scutcyr/SoulChat#4]

**Comment by qiuhuachuan** [comment]
> _No description provided._

For a large-scale and multi-turn dialogue dataset in mental health support, please see this repo https://github.com/qiuhuachuan/smile

**Comment by gaozhengjie** [comment]
> > _No description provided._
> 
> For a large-scale and multi-turn dialogue dataset in mental health support, please see this repo https://github.com/qiuhuachuan/smile

Thanks.

**Comment by MING-ZCH** [comment]
> > _No description provided._
> 
> 欢迎关注[EmoLLM](https://github.com/SmartFlowAI/EmoLLM/tree/main)，从专业数据到评估方法全部开源！

**Comment by wanghao07456** [comment]
> > > _No description provided._
> > 
> > 
> > 欢迎关注[EmoLLM](https://github.com/SmartFlowAI/EmoLLM/tree/main)，从专业数据到评估方法全部开源！

Thanks!

**Comment by scutcyr** [comment]
微调的数据集v0.1已开源，详见：https://www.modelscope.cn/datasets/YIRONGCHEN/SoulChatCorpus
