### ISSUE TITLE
求数据集，感谢🙏

### ISSUE THREAD

**Issue by ycp1027** [scutcyr/SoulChat#8]

**Comment by Farewell-CK** [comment]
佬，拿到数据集了嘛

**Comment by ycp1027** [comment]
> 佬，拿到数据集了嘛

没。。。

**Comment by xShuisheng** [comment]
同求数据集

**Comment by han508** [comment]
求数据集

**Comment by Farewell-CK** [comment]
佬们，我们开发了一个EmoLLM心理大模型,数据集目前公开了少部分（可用于局部微调），大量的数据集后续整理完成之后会进行公开。我们的项目地址：https://github.com/SmartFlowAI/EmoLLM
社群二维码：

**Comment by Farewell-CK** [comment]
如果二维码不能加载，可以在项目的issue中查看

**Comment by qiuhuachuan** [comment]
> > 佬，拿到数据集了嘛
> 
> 没。。。

可以看考这个仓库，这个数据集是开源的
https://github.com/qiuhuachuan/smile

**Comment by MING-ZCH** [comment]
欢迎关注[EmoLLM](https://github.com/SmartFlowAI/EmoLLM/tree/main)，从专业数据到评估方法全部开源，为中文心理咨询社区提供做出一些奉献！

**Comment by scutcyr** [comment]
微调的数据集v0.1已开源，详见：https://www.modelscope.cn/datasets/YIRONGCHEN/SoulChatCorpus

**Comment by scutcyr** [comment]
> _No description provided._

微调的数据集v0.1已开源，详见：https://www.modelscope.cn/datasets/YIRONGCHEN/SoulChatCorpus
